"""OnePiece Studio frontend package for local pandas and ASE database workbenches."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _package_version

try:
    __version__ = _package_version("onepiece-studio")
except PackageNotFoundError:  # pragma: no cover - only when run from a source tree
    __version__ = "0.0.0+unknown"

from onepiece.adsorption import (
    GasReferences,
    add_adsorption_energies,
    add_catalysis_hub_adsorption_energies,
    add_elemental_adsorption_energy,
    add_elemental_adsorption_free_energy,
    add_recipe_adsorption_energies,
    adsorption_view,
    assign_references_before_merge,
    assign_surface_references,
    copt_barrier_summary,
    copt_profile_points,
    default_room_temperature_phase,
    infer_adsorbate_recipe,
    infer_adsorption_recipes,
    infer_reference_equation_from_formula,
    parse_reference_equation,
)
from onepiece.ase_analysis import (
    add_ase_analysis_descriptors,
    adsorbate_orientation_angle,
    adsorbate_surface_distance_summary,
    classify_adsorption_site,
    compare_structures_rmsd,
    compute_d_band_center,
    compute_d_band_filling,
    coordination_numbers,
    detect_adsorbate_desorption,
    detect_adsorbate_dissociation,
    detect_overlapping_atoms,
    detect_unphysical_bonds,
    generalized_coordination_numbers,
    identify_surface_atom_indices,
    infer_atomic_layers,
    map_atoms_by_species_and_position,
    nearest_neighbor_distances,
    reaction_path_geometry_summary,
    slab_thickness,
    summarize_charge_transfer_by_layer,
    surface_reconstruction_metrics,
    vacuum_thickness,
)
from onepiece.automation import (
    add_structure_descriptors,
    annotate_reaction_network,
    apply_curation_rules,
)
from onepiece.dftdataframe_import import (
    add_input_parameter_checks,
    crawl_calculation_directories,
    crawl_calculation_paths,
    crawl_root_to_frame,
    crawl_root_to_hdf,
    create_calculation_frame,
    enrich_electronic_summaries,
    merge_entropies_file,
)
from onepiece.frame_utils import ensure_name_index, row_name
from onepiece.sources import apply_dataset_kind
from onepiece.storage import (
    DatasetManifest,
    StorageConfig,
    dataset_directory,
    dataset_manifest_path,
    detect_storage_format,
    ensure_storage_layout,
    load_dataset,
    read_dataset_manifest,
    resolve_storage_config,
    save_dataset,
)
from onepiece.thermo import add_gibbs_free_energy, adsorbate_free_energy, gas_free_energy
from onepiece.vasp import (
    ChgcarData,
    DoscarData,
    add_adsorbate_charge_descriptors,
    add_atomic_charge_descriptors,
    add_projected_dos_descriptors,
    adsorbate_atom_indices_from_structures,
    atomic_charge_long_table,
    compute_atomic_charges,
    doscar_projected_long_table,
    integrate_atomic_electron_populations,
    integrate_projected_dos,
    integrate_total_dos,
    matched_surface_atom_indices_from_structures,
    read_acf_dat,
    read_chgcar,
    read_doscar,
    read_vasp_valence_electrons,
)
from onepiece.xarray_vasp import (
    chgcar_cumulative_axis_profile,
    chgcar_line_profile,
    chgcar_planar_average,
    chgcar_plane_integrated_electrons,
    chgcar_to_xarray,
    doscar_integrated_pdos,
    doscar_orbital_band_center,
    doscar_select_energy_window,
    doscar_to_xarray,
)
from onepiece_studio.adapters import DatabaseSource, DataFrameSource, HDFSource, OnePieceSource
from onepiece_studio.config import ColumnConfig, OnePieceStudioConfig
from onepiece_studio.schema import ColumnKind, infer_schema

__all__ = [
    "ColumnConfig",
    "ColumnKind",
    "DataFrameSource",
    "DatabaseSource",
    "GasReferences",
    "HDFSource",
    "OnePieceSource",
    "OnePieceStudioConfig",
    "add_adsorption_energies",
    "add_ase_analysis_descriptors",
    "add_catalysis_hub_adsorption_energies",
    "add_elemental_adsorption_energy",
    "add_elemental_adsorption_free_energy",
    "add_recipe_adsorption_energies",
    "add_gibbs_free_energy",
    "adsorbate_orientation_angle",
    "adsorbate_surface_distance_summary",
    "adsorbate_free_energy",
    "adsorption_view",
    "atomic_charge_long_table",
    "classify_adsorption_site",
    "compare_structures_rmsd",
    "compute_d_band_center",
    "compute_d_band_filling",
    "coordination_numbers",
    "detect_adsorbate_desorption",
    "detect_adsorbate_dissociation",
    "detect_overlapping_atoms",
    "detect_unphysical_bonds",
    "assign_references_before_merge",
    "assign_surface_references",
    "default_room_temperature_phase",
    "ChgcarData",
    "DoscarData",
    "read_acf_dat",
    "read_chgcar",
    "read_doscar",
    "read_vasp_valence_electrons",
    "integrate_atomic_electron_populations",
    "compute_atomic_charges",
    "integrate_total_dos",
    "integrate_projected_dos",
    "chgcar_to_xarray",
    "chgcar_planar_average",
    "chgcar_plane_integrated_electrons",
    "chgcar_cumulative_axis_profile",
    "chgcar_line_profile",
    "doscar_to_xarray",
    "doscar_select_energy_window",
    "doscar_integrated_pdos",
    "doscar_orbital_band_center",
    "doscar_projected_long_table",
    "DatasetManifest",
    "StorageConfig",
    "dataset_directory",
    "dataset_manifest_path",
    "detect_storage_format",
    "add_atomic_charge_descriptors",
    "add_adsorbate_charge_descriptors",
    "add_projected_dos_descriptors",
    "matched_surface_atom_indices_from_structures",
    "adsorbate_atom_indices_from_structures",
    "copt_barrier_summary",
    "copt_profile_points",
    "generalized_coordination_numbers",
    "ensure_name_index",
    "ensure_storage_layout",
    "infer_adsorbate_recipe",
    "infer_adsorption_recipes",
    "infer_reference_equation_from_formula",
    "infer_schema",
    "identify_surface_atom_indices",
    "infer_atomic_layers",
    "map_atoms_by_species_and_position",
    "nearest_neighbor_distances",
    "reaction_path_geometry_summary",
    "slab_thickness",
    "summarize_charge_transfer_by_layer",
    "surface_reconstruction_metrics",
    "vacuum_thickness",
    "gas_free_energy",
    "parse_reference_equation",
    "annotate_reaction_network",
    "apply_curation_rules",
    "add_structure_descriptors",
    "apply_dataset_kind",
    "crawl_root_to_frame",
    "crawl_root_to_hdf",
    "add_input_parameter_checks",
    "crawl_calculation_directories",
    "crawl_calculation_paths",
    "create_calculation_frame",
    "enrich_electronic_summaries",
    "merge_entropies_file",
    "load_dataset",
    "read_dataset_manifest",
    "resolve_storage_config",
    "row_name",
    "save_dataset",
]
